services:
  backend:
    image: ghcr.io/eppy-team/eppy-be:latest 
    container_name: eppy-be-prod
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/src/main"