services:
  backend:
    build:
      context: .
      target: runner
    container_name: eppy-be-prod
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: sh -c "./node_modules/.bin/prisma migrate deploy && node dist/src/main"