services:
  db:
    image: pgvector/pgvector:pg16
    container_name: eppy-db-dev
    restart: always
    environment:
      POSTGRES_USER: eppy
      POSTGRES_PASSWORD: eppy123
      POSTGRES_DB: eppy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      target: builder 
    container_name: eppy-be-dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://eppy:eppy123@db:5432/eppy_db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma db push && npm run start:dev"

volumes:
  postgres_data_dev: