services:
  backend:
    build: 
      context: .
      target: runner 
    container_name: eppy-be-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    command: sh -c "node_modules/.bin/prisma migrate deploy && node dist/main"